export const mockCities = [
    { city: "Beijing", country: "China", code: "BJS", airport: "All Airports" },
    { city: "Beijing", country: "China", code: "PEK", airport: "Beijing Capital" },
    { city: "Beijing", country: "China", code: "PKX", airport: "Beijing Daxing" },
    { city: "Shanghai", country: "China", code: "SHA", airport: "All Airports" },
    { city: "Shanghai", country: "China", code: "PVG", airport: "Pudong Int'l" },
    { city: "Shanghai", country: "China", code: "SHA", airport: "Hongqiao Int'l" },
    { city: "London", country: "UK", code: "LON", airport: "All Airports" },
    { city: "London", country: "UK", code: "LHR", airport: "Heathrow" },
    { city: "London", country: "UK", code: "LGW", airport: "Gatwick" },
    { city: "New York", country: "USA", code: "NYC", airport: "All Airports" },
    { city: "New York", country: "USA", code: "JFK", airport: "John F. Kennedy" },
    { city: "New York", country: "USA", code: "EWR", airport: "Newark Liberty" },
    { city: "Tokyo", country: "Japan", code: "TYO", airport: "All Airports" },
    { city: "Tokyo", country: "Japan", code: "HND", airport: "Haneda" },
    { city: "Tokyo", country: "Japan", code: "NRT", airport: "Narita" },
    { city: "Los Angeles", country: "USA", code: "LAX", airport: "Los Angeles Int'l" },
    { city: "Paris", country: "France", code: "PAR", airport: "All Airports" },
    { city: "Paris", country: "France", code: "CDG", airport: "Charles de Gaulle" },
    { city: "Dubai", country: "UAE", code: "DXB", airport: "Dubai Int'l" },
    { city: "Singapore", country: "Singapore", code: "SIN", airport: "Changi" },
    { city: "Hong Kong", country: "China", code: "HKG", airport: "Hong Kong Int'l" },
    { city: "Sydney", country: "Australia", code: "SYD", airport: "Kingsford Smith" }
];
