import json
import urllib.request
import urllib.error
import math
from collections import defaultdict

# --- Configuration ---
COUNTRIES_URL = "https://restcountries.com/v3.1/all?fields=name,cca2,latlng,capital,region,population"
AIRPORTS_URL = "https://raw.githubusercontent.com/mwgg/Airports/master/airports.json"
# Using a slightly smaller cities dataset to ensure reliability, or we can filter a larger one. 
# cities15000.json contains cities > 15000 population, which is around 25k cities. Good enough for "Top 3".
CITIES_URL = "https://raw.githubusercontent.com/lutangar/cities.json/master/cities.json" 

OUTPUT_DIR = "src/data"
ENCODING = "utf-8"

def fetch_json(url):
    print(f"Fetching {url}...")
    try:
        req = urllib.request.Request(
            url, 
            data=None, 
            headers={
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
            }
        )
        with urllib.request.urlopen(req) as response:
            data = response.read().decode('utf-8')
            return json.loads(data)
    except urllib.error.URLError as e:
        print(f"Error fetching {url}: {e}")
        # Try reading error body if available
        if hasattr(e, 'read'):
             print(e.read().decode('utf-8'))
        return None

def write_js_file(filename, variable_name, data):
    # Sort data for consistency if list
    if isinstance(data, list):
        # customized sorting can be added here if needed
        pass
        
    path = f"{OUTPUT_DIR}/{filename}"
    print(f"Writing to {path}...")
    
    json_str = json.dumps(data, indent=4, ensure_ascii=False)
    # Remove quotes around keys? JS doesn't strictly require them but JSON does.
    # To make it strictly "JS", we can export it as valid JS.
    # The existing format is `export const VAR = [...]`.
    # JSON is valid JS object literal notation.
    
    content = f"// Generated by script\nexport const {variable_name} = {json_str};\n"
    
    with open(path, "w", encoding=ENCODING) as f:
        f.write(content)
    print(f"Done writing {filename}.")

def process_countries():
    raw_data = fetch_json(COUNTRIES_URL)
    if not raw_data:
        return None, None

    countries_js_list = []
    country_code_map = {} # cca2 -> common name
    country_info_map = {} # cca2 -> { capital: [str], population: int ... }

    for c in raw_data:
        name = c.get("name", {}).get("common", "")
        cca2 = c.get("cca2", "")
        latlng = c.get("latlng", [])
        
        if not name or not latlng:
            continue
            
        countries_js_list.append({
            "label": name,
            "lat": latlng[0],
            "lng": latlng[1]
        })
        
        country_code_map[cca2] = name
        country_info_map[cca2] = {
            "name": name,
            "capital": c.get("capital", []), # List of capital names
            "region": c.get("region", "")
        }

    # Sort alphabetcally
    countries_js_list.sort(key=lambda x: x["label"])
    
    write_js_file("countries.js", "COUNTRIES", countries_js_list)
    return country_code_map, country_info_map

import zipfile
import io

def process_cities(country_code_map, country_info_map):
    url = "http://download.geonames.org/export/dump/cities15000.zip"
    print(f"Fetching {url}...")
    try:
        req = urllib.request.Request(
             url, 
             headers={'User-Agent': 'Mozilla/5.0'}
        )
        with urllib.request.urlopen(req) as response:
            zip_content = response.read()
            
        with zipfile.ZipFile(io.BytesIO(zip_content)) as z:
            with z.open('cities15000.txt') as f:
                content = f.read().decode('utf-8')
                
        # Parse TSV
        # columns: geonameid(0), name(1), asciiname(2), alternatenames(3), lat(4), lng(5), ... country(8), ... population(14)
        
        cities_by_country = defaultdict(list)
        
        for line in content.splitlines():
            parts = line.split('\t')
            if len(parts) < 15:
                continue
                
            name = parts[1]
            lat = float(parts[4])
            lng = float(parts[5])
            cc = parts[8]
            try:
                pop = int(parts[14])
            except:
                pop = 0
                
            if pop <= 0:
                 continue
                 
            # Filter by valid country
            if cc not in country_code_map and cc not in country_info_map:
                 # Check if we should add anyway? 
                 # Maybe the user wants world cities.
                 # But keeping to valid countries is safer.
                 # Actually restcountries 'cca2' matches geonames country codes usually.
                 pass

            cities_by_country[cc].append({
                "name": name,
                "lat": lat,
                "lng": lng,
                "pop": pop
            })
            
    except Exception as e:
        print(f"Error processing cities zip: {e}")
        import traceback
        traceback.print_exc()
        return

    final_cities_list = []

    for cc, cities in cities_by_country.items():
        # Sort by population descending
        cities.sort(key=lambda x: x["pop"], reverse=True)
        
        # Get Country Info
        c_info = country_info_map.get(cc, {})
        capitals = c_info.get("capital", [])
        
        # Identify capitals in the list
        top_cities = cities[:3] # Top 3
        
        selected_cities = top_cities[:]
        
        # Add capitals if missing
        processed_names = {c["name"].lower() for c in selected_cities}
        
        for cap_name in capitals:
            if cap_name.lower() in processed_names:
                continue
                
            # Find in full list
            found = False
            for c in cities:
                if c["name"].lower() == cap_name.lower():
                    selected_cities.append(c)
                    processed_names.add(c["name"].lower())
                    found = True
                    break
            
            # If not found in cities list (maybe <15000 pop?), try to find ANY city with that name or skipping?
            # We can't add it without coords. restcountries sometimes has capitalInfo.latlng but I didn't verify if I fetched it.
            # I fetched 'fields=name,cca2,latlng,capital,region,population'.
            # I didn't fetch 'capitalInfo'.
            # It's safest to skip if not in major cities list, or just accept top 3.
        
        final_cities_list.extend(selected_cities)

    final_cities_list.sort(key=lambda x: x["name"])
    
    write_js_file("cities.js", "CITIES", final_cities_list)

def process_airports(country_code_map):
    raw_airports = fetch_json(AIRPORTS_URL) 
    # mwgg/Airports is a dict keyed by ICAO or IATA? 
    # Example format: 
    # "AAA": {
    #     "icao": "NTGA",
    #     "iata": "AAA",
    #     "name": "Anaa Airport",
    #     "city": "Anaa",
    #     "state": "Tuamotu-Gambier",
    #     "country": "PF",
    #     "elevation": 10,
    #     "lat": -17.3526001,
    #     "lon": -145.5099945,
    #     "tz": "Pacific/Tahiti"
    # }
    # It seems it is a Dictionary where Key is ICAO code usually, or IATA if available?
    # Actually wait, mwgg/Airports airports.json is a Dictionary indexed by ICAO code.
    
    if not raw_airports:
        return

    airports_list = []
    
    for icao, data in raw_airports.items():
        iata = data.get("iata", "")
        # Detailed user request: "supplement world's all airport data... format same as original"
        # Original format: { iata: "AMS", name: "Schiphol", city: "Amsterdam", country: "Netherlands", lat: 52.3086, lng: 4.7639 }
        # Note: Original uses full Country Name "Netherlands", not Code "NL".
        # mwgg data has country code "NL". I need to map it.
        
        if not iata or iata == "":
            continue # Skip airports without IATA code if they are just small airfields
            
        cc = data.get("country", "")
        country_name = country_code_map.get(cc, cc) # Fallback to code if name not found
        
        airports_list.append({
            "iata": iata,
            "name": data.get("name", ""),
            "city": data.get("city", data.get("name", "")), # Fallback city to name
            "country": country_name,
            "lat": float(data.get("lat", 0)),
            "lng": float(data.get("lon", 0))    # mwgg uses 'lon'
        })
        
    # Sort by IATA
    airports_list.sort(key=lambda x: x["iata"])
    
    write_js_file("airports.js", "AIRPORTS", airports_list)

def main():
    print("Starting data generation...")
    
    # 1. Countries
    # We need country codes map for airports and cities too
    map_code_name, map_code_info = process_countries()
    
    if map_code_name:
        # 2. Cities
        process_cities(map_code_name, map_code_info)
        
        # 3. Airports
        process_airports(map_code_name)
    
    print("All tasks completed.")

if __name__ == "__main__":
    main()
